---
sidebar: sidebar 
permalink: vcp_task_reports_qossioc.html 
summary: Você pode exibir informações sobre sessões iSCSI conetadas ao cluster selecionado no plug-in do NetApp Element para VMware vCenter Server. 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, qossioc, cluster, performance 
---
= Monitore a disposição em camadas de performance da VM com eventos do QoSSIOC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode exibir eventos relacionados ao QoSSIOC quando uma VM com um datastore habilitado para QoS é reconfigurada ou emitida um evento de energia ou convidado.

Você pode visualizar eventos do QoSSIOC a partir do ponto de extensão do plug-in do NetApp Element Plug-in para vCenter Server.

Os eventos de QoSSIOC são exibidos a partir de clusters adicionados localmente. Em um ambiente de modo vinculado, faça login no vSphere Web Client que tem o cluster adicionado localmente para exibir eventos do QoSSIOC para esse cluster.

[NOTE]
====
* A partir do plug-in Element vCenter 5,0, para usar link:vcp_concept_linkedmode.html["Modo vinculado do vCenter"]o , você Registra o plug-in Element a partir de um nó de gerenciamento separado para cada vCenter Server que gerencia clusters de storage do NetApp SolidFire.
* O uso do plug-in do NetApp Element para vCenter Server 4,10 e anterior para gerenciar recursos de cluster de outros vCenter Servers que usam link:vcp_concept_linkedmode.html["Modo vinculado do vCenter"] é limitado apenas a clusters de storage locais.


====
.O que você vai precisar
* Pelo menos um cluster deve ser adicionado e executado.
* O serviço QoSSIOC deve ser configurado e verificado em execução usando a página Configurações de QoSSIOC para o plug-in.
* Pelo menos um datastore deve ter a automação do QoSSIOC ativada.


.Passos
. No seu vSphere Web Client, abra a guia *QoSSIOC Events*:
+
** A partir do plug-in Element vCenter 5,0, selecione *Plugin remoto NetApp Element > Configuração > Eventos de QoSSIOC*.
** Para o plug-in do Element vCenter 4,10 e anterior, selecione *Configuração do NetApp Element > Eventos de QoSSIOC*.






== Dados de eventos da QoSSIOC

* *Data*: A data e hora do evento QoSSIOC.
* *Nome do datastore*: O nome do datastore definido pelo usuário.
* *Cluster IP*: O endereço IP do cluster que contém o datastore do qual o evento se originou.
* *ID de volume*: O ID gerado pelo sistema para o volume associado.
* *IOPs mínimos*: A configuração atual de QoS de IOPS mínimo do volume.
* *IOPs máx*: A configuração atual de QoS máximo de IOPS do volume.
* *IOPs Burst*: A configuração atual de QoS de burst máximo do volume.
* *Burst Time*: O período de tempo em que uma explosão é permitida.




== Encontre mais informações

* https://docs.netapp.com/us-en/hci/index.html["Documentação do NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Página de recursos do SolidFire e do Element"^]

